default_context:
  full_name: "Jonas Pammer"
  email: "opensource@jonaspammer.at"
  github_username: "JonasPammer"
  code_of_conduct_enforcement_contact_email: "opensource@jonaspammer.at"

  project_name: "Some Package"
  project_short_description: "An Python Package for..."

  dockerhub_username: "JonasPammer"
  pypi_username: "jonaspammer"
  use_automated_pypi_deployment: "y"
  command_line_interface: "Click"
  use_pytest: "y"