= CookieCutter Python Package
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 3
:toc-placement!:

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


[subs="+quotes,attributes"]
----
user@machine:~/dev$ *cruft create https://github.com/JonasPammer/cookiecutter-pypackage.git*
----

== Features

=== At-a-Glance

* Formatting with https://github.com/psf/black[black]
and https://prettier.io/[prettier]
* Import sorting with https://github.com/asottile/reorder_python_imports[reorder-python-imports]
(https://github.com/timothycrosley/isort[isort] alternative)
* Static typing with http://mypy-lang.org/[mypy]
* Linting with http://flake8.pycqa.org/en/latest/[flake8]
* Git hooks that run all the above with pre-commit
* Testing with https://docs.pytest.org/en/latest/[pytest] and tox
* Deployment ready with Docker [TODO]
* Continuous Integration with https://github.com/features/actions[GitHub Actions]

=== General

* Includes an Awesome README
+
[NOTE]
====
Because
https://github.com/github/markup/issues/1095[github/markup#1095 (support include directives for other asciidoc files)],
is still not fixed, the following measures were taken:

* Every block that contains an `include` has an associated `link`.
* The README exists as an automatically published GitHub Page, of which the HTML was generated by Asciidoctor (= done right).
** The Preamble of the generated Projects' README includes a link to this single-page README,
which is displayed only when viewed from GitHub.

[NOTE]
=====
*You need to* activate the _Pages_ feature on a per-repository basis.

To do so, go to the _Settings_ page of your GitHub repository. Under _Pages / Source_, select [`gh-pages`] [`/ (root)`], and click _Save_.
=====
====
* Includes a Beginner-Friendly Development Documentation file
* Includes a Beginner-Friendly Contribution Documentation file, inspired by
  https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md[Auth0's Open Source Template].
* Assumes MIT License.
* Includes numerous https://pre-commit.com/[pre-commit] hooks to automatically
  find linting issues, format your files, and find common issues of version control and source code
* Includes a very much standard
  https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration[`yamllint` configuration]
  (enforced through pre-commit and checked by CI)
* Assumes enforcement of
  https://gist.github.com/JonasPammer/4ea577854ae10afe644bff366d7b2a8a[Conventional Commit]
  (checked by a pre-commit hook if activated)
+
[IMPORTANT]
====
The resulting projects mentions that this is completely optional for casual contributors,
as *it is assumed that pull requests are squash-merged by maintainers*.
====
* Includes a exhaustive `.gitignore` file generated by https://www.toptal.com/developers/gitignore[gitignore.io]
* Includes a copy of the
  https://www.contributor-covenant.org/version/2/0/code_of_conduct/[Contributor Covenant Code of Conduct] as generated automatically by GitHub.


=== GitHub

[NOTE]
====
The resulting projects mentions that `pre-commit` installation is optional,
as it is assumed that the project is included in your `pre-commit.ci` account projects.
====

* Includes a `.gitattributes` file, ensuring LF line endings
* Includes GitHub *Issue Form Templates* for filing bug reports and feature requests using HTML forms
* Includes a GitHub *Pull Request Template*
* Includes a Continuous GitHub Workflow to *automatically stale/close issues and PRs* that have had no activity (updates or comments) for 30/7 days respectively.
* Includes a GitHub Workflow to denote size of pull requests by automagically labelling them
* Includes a
  https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates[Dependabot]
  configuration file to check for updates of used GitHub Actions themselves on a monthly basis
* Includes a GitHub Workflow to *declaratively manage labels*
** The predefined `labels.json` is inspired by the kubernetes project