= CookieCutter Python Package
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 2
:toc-placement!:
:cc-example-name: my-python-project

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


https://github.com/JonasPammer/cookiecutter-pypackage/actions/workflows/ci.yml[image:https://github.com/JonasPammer/cookiecutter-pypackage/actions/workflows/ci.yml/badge.svg[CI Status]]

Awesome https://github.com/cookiecutter/cookiecutter[Cookiecutter] template for creating Python Packages.

toc::[]


== Primary Features

=== At-a-glance

// pre-commit

* Formatting with https://github.com/psf/black[black],
  https://github.com/PyCQA/docformatter[docformatter] and
  https://prettier.io/[prettier]
* Import sorting with https://github.com/asottile/reorder_python_imports[reorder-python-imports]
  (https://github.com/timothycrosley/isort[isort] alternative)
* Static typing with http://mypy-lang.org/[mypy]
* Linting with http://flake8.pycqa.org/en/latest/[flake8]
* Git hooks that run all the above with https://pre-commit.com/[pre-commit]

---

* Continuous Integration with https://github.com/features/actions[GitHub Actions]
* Testing with https://docs.pytest.org/en/latest/[pytest] (preferred) or unittest (optional)
  and https://github.com/tox-dev/tox[tox]
* Code Coverage Reporting with https://about.codecov.io/[Codecov] through CI

---

* Assumes Minimum Python Version of 3.7
* Command line interface using argparse or Click (optional)
* Automatic build-and-release to https://pypi.org/[PyPI] when pushing a new tag to master
* Deployment / Execution ready through Dockerfile that follows all best-practices
  (https://github.com/hexops/dockerfile/tree/aed47f5b4c7a923510e57019d3e4f0ee80006d78[1],
   https://pythonspeed.com/docker/[2])

=== GitHub

* Includes a GitHub Workflow to automatically build, tag and push the Project's Dockerfile to DockerHub
+
[NOTE]
====
*Requires* the secrets `DOCKERHUB_TOKEN` and `DOCKERHUB_PASSWORD`
to be present in the GitHub repository or organization!
====
+
[NOTE]
====
The docker image is automatically tagged using
https://github.com/docker/metadata-action[docker/metadata-action]
in below format (based on the SemVer example):

|===
| Event | Ref (Action Input) | Docker Tags

| `pull_request`
| `refs/pull/2/merge`
| `pr-2`

| `push`
| `refs/heads/master`
| `master`

// TODO add example for sha

| `push`
| `refs/heads/releases/v1`
| `releases-v1`

| `push tag`
| `refs/tags/v1.2.3`
| `1.2.3`,
  `1.2`,
  `latest`

| `push tag`
| `refs/tags/v2.0.8-beta.67`
| `2.0.8-beta.67`
|===

[NOTE]
Tags not starting with `v` are not processed by this GitHub Workflow.
====

=== PyPI

* Includes a GitHub Workflow to automatically build and upload the package to PyPI.
+
[NOTE]
====
*Requires* the secrets `PYPI_API_KEY`
to be present in the GitHub repository or organization!
====

=== Development

* Versions are managed through tags
  which can be simply bumped using https://github.com/c4urself/bump2version[`bump2version`].

== Usage

First, get https://github.com/cruft/cruft[Cruft].
It's a tool built in Cookiecutter that will allow you to keep up-to-date with the changes made to this cookiecutter.

[subs="+quotes,attributes"]
----
$ *python3 -m pip install cruft*
----

Now run it against this repo:

[subs="+quotes,attributes"]
----
$ *cruft create https://github.com/JonasPammer/cookiecutter-pypackage.git*
----

Answer the prompts with your own desired options.

Enter the project and take a look around
(replace "{cc-example-name}" with your project slug):

[subs="+quotes,attributes"]
----
$ *cd ##{cc-example-name}##*
~/##{cc-example-name}##$ *ls*
----

Create a git repo and push it there
(replace "YourGitHubName" with your github profile name
 and "{cc-example-name}" with your project slug):

[subs="+quotes,attributes"]
----
~/##{cc-example-name}##$ *git init*
~/##{cc-example-name}##$ *git add .*
~/##{cc-example-name}##$ *git commit -m "chore: create from cookiecutter"*
~/##{cc-example-name}##$ *git remote add origin git@github.com:##YourGitHubName/{cc-example-name}##.git*
~/##{cc-example-name}##$ *git push -u origin master*
----

Now take a look at your repo.
Don't forget to carefully look at the generated README -
It contains all relevant Development Documentation.

Awesome, right?

[NOTE]
This CookieCutter does not configure your GitHub Repository.
Please read the notes found in this README and perform the documented manual steps
(e.g., Creating GitHub Action Secrets).


== Generic Features of this 🍪

I maintain several CookieCutter's.
Many of them share a similiar set of boilerplate files.
You will find this section to be the same in most of them.

=== Documentation

* Includes an Awesome README
+
[NOTE]
====
Because
https://github.com/github/markup/issues/1095[github/markup#1095 (support include directives for other asciidoc files)]
is still not fixed, the following measures were taken:

* `README.orig.adoc` is the actual README that must be edited. +
A GitHub Workflow takes care of generating the actual `README.adoc` using the official tool
https://github.com/asciidoctor/asciidoctor-reducer[`ascidoctor-reducer`].
* [optional] The README also exists as an automatically published GitHub Page, of which the HTML was generated by Asciidoctor (= done right).
+
[NOTE]
=====
For this to work, *you need to* activate the _Pages_ feature on a per-repository basis.

To do so, go to the _Settings_ page of your GitHub repository. Under _Pages / Source_, select [`gh-pages`] [`/ (root)`], and click _Save_.
=====
====
* Includes a Beginner-Friendly Development Documentation file
* Includes a Beginner-Friendly Contribution Documentation file, inspired by
  https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md[Auth0's Open Source Template].

=== Development

* Assumes MIT License.
* Changelog is assumed to be managed through the use of GitHub Releases.
* Includes numerous https://pre-commit.com/[pre-commit] hooks to automatically
  find linting issues, format your files, and find common issues of version control and source code
* Includes a very much standard
  https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration[`yamllint` configuration]
  (enforced through pre-commit and checked by CI)
* Assumes enforcement of
  https://github.com/JonasPammer/JonasPammer/blob/master/demystifying/conventional_commits.adoc[Conventional Commit]
  (checked by a pre-commit hook if activated)
+
[IMPORTANT]
====
The resulting projects mentions that this is completely optional for casual contributors,
as *it is assumed that pull requests are squash-merged by maintainers*.
====
* Includes a exhaustive `.gitignore` file generated by https://www.toptal.com/developers/gitignore[gitignore.io]
* Includes a copy of the
  https://www.contributor-covenant.org/version/2/0/code_of_conduct/[Contributor Covenant Code of Conduct] as generated automatically by GitHub.


=== GitHub

[NOTE]
====
The resulting projects mentions that `pre-commit` installation is optional,
as it is assumed that the project is included in your `pre-commit.ci` account projects.
====

* Includes a `.gitattributes` file, ensuring LF line endings
* Includes GitHub *Issue Form Templates* for filing bug reports and feature requests using HTML forms
* Includes a GitHub *Pull Request Template*
* Includes a Continuous GitHub Workflow to *automatically stale/close issues and PRs* that have had no activity (updates or comments) for 30/7 days respectively.
* Includes a GitHub Workflow to denote size of pull requests by automagically labelling them
* Includes a
  https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates[Dependabot]
  configuration file to check for updates of used GitHub Actions themselves on a monthly basis
* Includes a GitHub Workflow to *declaratively manage labels*
** The predefined labels definition is inspired by the kubernetes project
