---
name: build self-contained READMEs

"on":
  push:

permissions:
  contents: read

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      ### Setup
      - name: check out the codebase
        uses: actions/checkout@v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.0"

      - name: set up python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: setup/activate pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: "{% raw %}${{ hashFiles('.pre-commit-config.yaml') }}{% endraw %}"

      - name: install asciidoctor and other relevant ruby gems
        run: gem install --no-document asciidoctor asciidoctor-reducer rouge coderay

      - name: get first line of commit message as variable
        shell: bash
        run: |
          echo "FIRST_LINE_OF_HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}" | head -1 >> $GITHUB_ENV
        env:
          HEAD_COMMIT_MESSAGE: "{% raw %}${{ github.event.head_commit.message }}{% endraw %}"

      ### README.orig.adoc & co.
      - name: Generate README.adoc using ascidoctor-reducer.
        run: asciidoctor-reducer README.orig.adoc -o README.adoc

      - name: generate README.xml from README.adoc using ascidoctor
        run: asciidoctor -b docbook README.adoc

      - name: Generate README.md from README.xml using pandoc
        uses: docker://pandoc/core:3.1
        with:
          args: "-f docbook -t markdown_strict README.xml -o README.md --wrap=none"

      ### SECURITY.adoc
      - name: generate SECURITY.xml from SECURITY.adoc using ascidoctor
        run: asciidoctor -b docbook SECURITY.adoc

      - name: Generate SECURITY.md from SECURITY.xml using pandoc
        uses: docker://pandoc/core:3.1
        with:
          args: "-f docbook -t markdown_strict SECURITY.xml -o SECURITY.md --wrap=none"

      ### Commit
      - name: add 'changes will be lost' comment to generated files
        run: |
          sed -i '1s/^/This file is being generated by .github/workflows/gh-pages.yml - all local changes will be lost eventually! /' README.adoc README.md SECURITY.md

      - name: pre-commit generated .md files
        run: |
          python3 -m pip install pre-commit
          pre-commit run --files README.md SECURITY.md || true
          pre-commit run --files README.md SECURITY.md || true

      - name: Commit generated files.
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "{% raw %}${{ env.FIRST_LINE_OF_HEAD_COMMIT_MESSAGE }}{% endraw %}\n{% raw %}${{ github.sha }}{% endraw %}"
          file_pattern: README.adoc README.md SECURITY.md
          disable_globbing: true

      ### Deploy README.adoc
      - name: Generate HTML
        run: asciidoctor --backend=html5 --destination-dir docs --out-file index.html README.adoc

      - name: Deploy HTML to GitHub Pages (when branch is master).
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"
          publish_branch: gh-pages
          publish_dir: ./docs/
        if: github.ref == 'refs/heads/master'
