---
name: create declared labels

"on":
  issues:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/issue-label-manager.yml"
      - ".github/labels.yml"

permissions:
  contents: read

jobs:
  labels:
    name: Invoke issue-label-manager action
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crazy-max/ghaction-github-labeler@v4
        if: success()
        with:
          github-token: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"
          yaml-file: .github/labels.yml
          skip-delete: false # false -> delete labels that aren't in `yaml-file`
