---
name: create declared labels

"on":
  issues:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/issue-label-manager.yml"
      - ".github/labels.yml"

permissions:
  contents: read

jobs:
  labels:
    name: Invoke issue-label-manager action
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: crazy-max/ghaction-github-labeler@77450f9fa47c41fbab15c0923417fff00730ffa3 # tag=v4
        if: success()
        with:
          github-token: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"
          yaml-file: .github/labels.yml
          skip-delete: false # false -> delete labels that aren't in `yaml-file`
