= {{ cookiecutter.project_name }}
{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>;

https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/actions/workflows/docker.yml[image:https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/actions/workflows/docker.yml/badge.svg[Docker Workflow Status]]

This image can be used to run
https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}[{{ cookiecutter.project_slug }}].


== Run
:base_command: docker run --rm -it {{ cookiecutter.dockerhub_username }}/{{ cookiecutter.project_slug }}

.Running the latest release
[subs="quotes,attributes"]
----
{base_command} *[--help | ...]*
----

.Running a given release
[subs="quotes,attributes"]
----
{base_command}:v1.0 *[--help | ...]*
----

.Running the latest development version (https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/actions/workflows/ci.yml[image:https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/actions/workflows/ci.yml/badge.svg[CI Status]])
[subs="quotes,attributes"]
----
{base_command}:master *[--help | ...]*
----

=== Tags



== Source Repository

https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}